
- name: Playbook for installing Monitoring software (mysql-server + zabbix + grafana)
  gather_facts: false
  hosts: 127.0.0.1
  become: yes
  tasks:

    - name: Install software for monitoring server
      yum:
        name: 
          - docker
          - vim
          - python-pip
        state: present

    - name: Configuring docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install pip libraries dependencies 
      pip:
        name: docker

    - name: Create mysql-server-data volume
      docker_volume:
        name: mysql-server-data

    - name: Create grafana-config volume
      docker_volume:
        name: grafana-config

    - name: Create grafana-storage volume
      docker_volume:
        name: grafana-storage

    - name: Create mysql-net network
      docker_network:
        name: mysql-net
        attachable: yes

    - name: Create zabbix-net network
      docker_network:
        name: zabbix-net
        attachable: yes

    - name: Create grafana-net network
      docker_network:
        name: grafana-net
        attachable: yes

    - name: Creating MYSQL-SERVER container
      docker_container:
        name: mysql-server
        state: started
        image: mysql:8.0
        volumes:
        - "mysql-server-data:/var/lib/mysql:rw"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_bin  --default-authentication-plugin=mysql_native_password
        restart_policy: unless-stopped
        purge_networks: yes
        networks:
        - name: mysql-net
        user: mysql
        env:
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix_pwd"
          MYSQL_ROOT_PASSWORD: "root_pwd"
          
    - name: Attach mysql-server container to zabbix network
      docker_network:
        name: zabbix-net
        connected:
          - mysql-server
        appends: yes
            
    - name: Creating ZABBIX-SERVER container
      docker_container:
        name: zabbix-server
        state: started
        image: zabbix/zabbix-server-mysql:latest
        purge_networks: yes
        networks:
        - name: zabbix-net
        links:
        - "mysql-server:mysql"
        volumes:
        - "mysql-server-data:/var/lib/mysql:rw"
        ports:
        - "10051:10051"
        restart_policy: unless-stopped
        env:
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix_pwd"
          DB_SERVER_HOST: "mysql-server"

    - name: Creating ZABBIX-WEB container
      docker_container:
        name: zabbix-web
        state: started
        image: zabbix/zabbix-web-apache-mysql:latest
        purge_networks: yes
        networks:
        - name: zabbix-net
        links:
        - "mysql-server:mysql"
        - "zabbix-server:zabbix-server"
        volumes:
        - "mysql-server-data:/var/lib/mysql:rw"
        ports:
        - "80:8080"
        restart_policy: unless-stopped
        env:
          MYSQL_DATABASE: "zabbix"
          MYSQL_USER: "zabbix"
          MYSQL_PASSWORD: "zabbix_pwd"
          DB_SERVER_HOST: "mysql-server"

    - name: Creating GRAFANA container
      docker_container:
        name: grafana
        hostname: grafana.ccelmoro.com.ar
        state: started
        image: grafana/grafana:latest
        purge_networks: yes
        networks:
        - name: grafana-net
        links:
        - "mysql-server:mysql"
        - "zabbix-server:zabbix-server"
        volumes:
        - "grafana-config:/etc/grafana:rw"
        - "grafana-storage:/var/lib/grafana/:rw"
        ports:
        - "3000:3000"
        restart_policy: unless-stopped

    - name: Attach grafana-server container to zabbix network
      docker_network:
        name: zabbix-net
        connected:
          - grafana
        appends: yes

    - name: Check if grafana plugin for zabbix was installed
      #command: docker exec grafana grafana-cli plugins install alexanderzobnin-zabbix-app
      shell: docker exec grafana grafana-cli plugins ls | grep alexanderzobnin-zabbix-app
      register: plugininstalled
      ignore_errors: yes

    - name: Installing grafana plugin for zabbix
      command: docker exec grafana grafana-cli plugins install alexanderzobnin-zabbix-app
      #command: docker exec grafana grafana-cli plugins ls | grep alexanderzobnin-zabbix-app
      when: plugininstalled.rc > 0
      notify:
      - restart grafana container

  handlers:
    - name: restart grafana container
      command: docker restart grafana